services:

  app:
    build: .
    command: >
      bash -c "rm -f tmp/pids/server.pid &&
               bundle check || bundle install &&
               bundle exec rails s -p 3000 -b '0.0.0.0'"
    depends_on:
      - database
      - redis
    volumes:
      - .:/usr/src/app
      - storage_data:/var/www/app_storage
      - gems_volume:/gems:cached
    env_file:
      - .env/development/web
      - .env/development/database
    ports:
      - 4001:3000

  redis:
    image: redis:7.2.4
    expose:
      - 6379
    volumes:
      - redis_data:/data

  database:
    image: postgres:16.2
    env_file:
      - .env/development/database
    expose:
      - 5432  
    volumes:
      - db_data:/var/lib/postgresql/data

  # pgadmin:
  #   image: dpage/pgadmin4:latest
  #   env_file:
  #     - .env/development/pgadmin
  #   ports:
  #     - 5555:80
  #   volumes:
  #     - pgadmin-data:/var/lib/pgadmin

volumes:
  db_data:
  redis_data:
  storage_data:
  gems_volume:
  # pgadmin-data:
